pipeline:
  identifier: Build_mainsail44_caldera_1706368622043
  name: Build caldera
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706368592187
        repoName: mainsail44/caldera
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1706368592187
                    repoName: https://github.com/mainsail44/caldera.git --recursive
                    build:
                      type: branch
                      spec:
                        branch: master
                  description: https://github.com/mainsail44/caldera.git
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: mainsailindustries / caldera
                    tags:
                      - latest
                    buildArgs:
                      WIN_BUILD: "true"
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: docker run -p 8888:8888 caldera:latest
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
